### ISSUE TITLE
Reskin items are not marked as dps

### ISSUE THREAD

**Issue by Waifu** [Waifu/OsancTools#3]
### Issue
Some reskins of items are not counted as dps in the react parse, an example is the [Ice Crown](https://www.realmeye.com/wiki/ice-crown), which is a reskin of the [Forgotten Crown](https://www.realmeye.com/wiki/the-forgotten-crown).  

From the chart below, this reskin should count as a dps item:

![image](https://user-images.githubusercontent.com/58831335/186929673-5571413f-a855-48e9-9c73-4b74d000859a.png)

### Screenshots and/or videos
![image](https://user-images.githubusercontent.com/58831335/186957976-b37667f2-eb6a-4888-a171-13404cfee915.png)

### Operating System
Windows 11

### Version
OsancTools v1.0

**Comment by kkkesilchen** [comment]
yo

**Comment by Waifu** [comment]
fixed with #4
