### ISSUE TITLE
Bad reaction overwrites inventory and message

### ISSUE THREAD

**Issue by kkkesilchen** [Waifu/OsancTools#8]
### Issue
The inventory and message of an user, who reacted as a rune, are overwritten by a bad reaction
Example id for below: 16759.
### Screenshots and/or videos
![image](https://user-images.githubusercontent.com/92551892/201498127-d0ff399a-afc1-4b4e-9da2-f5cfc1e386ad.png)

### Version
OsancTools v1.0.0.3

**Comment by Waifu** [comment]
Fixed with https://github.com/Waifu/OsancTools/commit/f4c93aa4c4d83a989bd4fc3bc91b923c5c4a83f7
